import type { RegistrationRecord } from "@/types/student/enrollment"

export const dummyRegistrationRecords: Record<string, RegistrationRecord> = {
  "210047": {
    studentNumber: "210047",
    schoolYear: "2026-2027",
    semester: "1st Semester",
    courseSection: "BSIT - A",
    yearLevel: "4th Year",
    dateOfRegistration: "May 19, 2026",
    processedBy: "Mae Haedeline B. Buenavente, LPT",
    assessedBy: "Rosalinda Aguilar",
    approvedBy: "Niña Lovella B. Mijares",
    subjects: [
      {
        code: "APC 7",
        description: "System Administration & Maintenance",
        units: 3,
        classTime: "07:30-09:00",
        days: "T,TH",
        instructor: "M. Abuke",
      },
      {
        code: "APC 8",
        description: "Business Outsourcing",
        units: 3,
        classTime: "09:00-10:30",
        days: "T,TH",
        instructor: "C. Gales",
      },
      {
        code: "CAPS 420",
        description: "Capstone Project 2",
        units: 3,
        classTime: "01:00-02:30",
        days: "T,TH",
        instructor: "M. Abuke",
      },
    ],
    assessment: {
      tuitionRatePerUnit: 250,
      tuitionUnits: 9,
      labRatePerUnit: 150,
      labUnits: 3,
      amountPaid: 0,
      orNumber: "0",
      miscFees: [
        { label: "Registration", amount: 500 },
        { label: "Library", amount: 200 },
        { label: "Dental", amount: 200 },
        { label: "Athletic", amount: 150 },
        { label: "ID Card", amount: 0 },
        { label: "SSC", amount: 150 },
        { label: "Testing Materials", amount: 500 },
        { label: "Student Handbook", amount: 0 },
        { label: "Charity", amount: 100 },
        { label: "RedCross", amount: 200 },
        { label: "Insurance", amount: 150 },
        { label: "Publication", amount: 200 },
        { label: "Sports Development", amount: 200 },
        { label: "PRISAA", amount: 200 },
        { label: "Guidance", amount: 150 },
        { label: "Medical", amount: 200 },
        { label: "Development Fee", amount: 0 },
      ],
    },
  },

  "2026-00002": {
    studentNumber: "2026-00002",
    schoolYear: "2026-2027",
    semester: "1st Semester",
    courseSection: "BSHM - A",
    yearLevel: "2nd Year",
    dateOfRegistration: "May 20, 2026",
    processedBy: "Mae Haedeline B. Buenavente, LPT",
    assessedBy: "Rosalinda Aguilar",
    approvedBy: "Niña Lovella B. Mijares",
    subjects: [
      {
        code: "HM 201",
        description: "Front Office Operations",
        units: 3,
        classTime: "08:00-09:30",
        days: "M,W",
        instructor: "J. Salcedo",
      },
      {
        code: "HM 202",
        description: "Housekeeping Management",
        units: 3,
        classTime: "10:00-11:30",
        days: "M,W",
        instructor: "R. Villamor",
      },
    ],
    assessment: {
      tuitionRatePerUnit: 250,
      tuitionUnits: 6,
      labRatePerUnit: 150,
      labUnits: 2,
      amountPaid: 3000,
      orNumber: "OR-88213",
      miscFees: [
        { label: "Registration", amount: 500 },
        { label: "Library", amount: 200 },
        { label: "Dental", amount: 200 },
        { label: "Athletic", amount: 150 },
        { label: "Insurance", amount: 150 },
        { label: "Guidance", amount: 150 },
        { label: "Medical", amount: 200 },
      ],
    },
  },

  "2026-00003": {
    studentNumber: "2026-00003",
    schoolYear: "2026-2027",
    semester: "1st Semester",
    courseSection: "BSOA - A",
    yearLevel: "3rd Year",
    dateOfRegistration: "May 21, 2026",
    processedBy: "Mae Haedeline B. Buenavente, LPT",
    assessedBy: "Rosalinda Aguilar",
    approvedBy: "Niña Lovella B. Mijares",
    subjects: [
      {
        code: "OA 301",
        description: "Records Management",
        units: 3,
        classTime: "01:00-02:30",
        days: "T,TH",
        instructor: "L. Domingo",
      },
      {
        code: "OA 302",
        description: "Office Systems & Technology",
        units: 3,
        classTime: "03:00-04:30",
        days: "T,TH",
        instructor: "F. Amoyo",
      },
    ],
    assessment: {
      tuitionRatePerUnit: 250,
      tuitionUnits: 6,
      labRatePerUnit: 150,
      labUnits: 2,
      amountPaid: 5800,
      orNumber: "OR-88214",
      miscFees: [
        { label: "Registration", amount: 500 },
        { label: "Library", amount: 200 },
        { label: "Athletic", amount: 150 },
        { label: "Insurance", amount: 150 },
        { label: "Guidance", amount: 150 },
      ],
    },
  },
  "230460": {
    studentNumber: "230460",
    schoolYear: "2026-2027",
    semester: "1st Semester",
    courseSection: "BSIT - A",
    yearLevel: "4th Year",
    dateOfRegistration: "May 19, 2026",
    processedBy: "Mae Haedeline B. Buenavente, LPT",
    assessedBy: "Rosalinda Aguilar",
    approvedBy: "Niña Lovella B. Mijares",
    subjects: [
      {
        code: "APC 7",
        description: "System Administration & Maintenance",
        units: 3,
        classTime: "07:30-09:00",
        days: "T,TH",
        instructor: "M. Abuke",
      },
      {
        code: "APC 8",
        description: "Business Outsourcing",
        units: 3,
        classTime: "09:00-10:30",
        days: "T,TH",
        instructor: "C. Gales",
      },
      {
        code: "CAPS 420",
        description: "Capstone Project 2",
        units: 3,
        classTime: "01:00-02:30",
        days: "T,TH",
        instructor: "M. Abuke",
      },
    ],
    assessment: {
      tuitionRatePerUnit: 250,
      tuitionUnits: 9,
      labRatePerUnit: 150,
      labUnits: 3,
      amountPaid: 0,
      orNumber: "0",
      miscFees: [
        { label: "Registration", amount: 500 },
        { label: "Library", amount: 200 },
        { label: "Dental", amount: 200 },
        { label: "Athletic", amount: 150 },
        { label: "ID Card", amount: 0 },
        { label: "SSC", amount: 150 },
        { label: "Testing Materials", amount: 500 },
        { label: "Student Handbook", amount: 0 },
        { label: "Charity", amount: 100 },
        { label: "RedCross", amount: 200 },
        { label: "Insurance", amount: 150 },
        { label: "Publication", amount: 200 },
        { label: "Sports Development", amount: 200 },
        { label: "PRISAA", amount: 200 },
        { label: "Guidance", amount: 150 },
        { label: "Medical", amount: 200 },
        { label: "Development Fee", amount: 0 },
      ],
    },
  },
}