import type { Transcript } from "@/types/student/grades"

export const dummyTranscripts: Record<string, Transcript> = {
  "230460": {
    studentNumber: "230460",
    studentName: "Atencio, Rio Umanga",
    course: "BSIT",
    yearLevel: "4th Year",
    curriculum: "2023",
    totalEarnedUnits: 149.0,
    semesters: [
      {
        schoolYear: "2023-2024",
        semester: "1st Semester",
        totalUnits: 26,
        entries: [
          { code: "MATH PREP", title: "Pre-Calculus for Non-STEM (Algebra & Trigonometry)", instructor: "L. Hena", finalGrade: 2.5, completedGrade: null, units: 3 },
          { code: "NSTP 110", title: "National Service Training Program 1", instructor: "N. Canoza", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "GE 111", title: "Ang Panitikan ng Pilipinas", instructor: "M. Corocoto", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "GE 113", title: "Science, Technology and Society", instructor: "J. Gatongay", finalGrade: 2.5, completedGrade: null, units: 3 },
          { code: "GE 112", title: "Mathematics in the Modern World", instructor: "L. Eufracio", finalGrade: 2.0, completedGrade: null, units: 3 },
          { code: "GE 110", title: "Understanding the Self", instructor: "C. Liza", finalGrade: 1.25, completedGrade: null, units: 3 },
          { code: "ITE 110", title: "Introduction to Computing", instructor: "V. Camposano", finalGrade: 1.75, completedGrade: null, units: 3 },
          { code: "ITE 111", title: "Computer Programming 1 (C Language)", instructor: "S. Zarmia Arby", finalGrade: 2.0, completedGrade: null, units: 3 },
          { code: "PATHFIT 1", title: "Physical Activities Toward Health and Fitness 1 (Movement Competency Training)", instructor: "M. Mercader", finalGrade: 2.25, completedGrade: null, units: 2 },
        ],
      },
      {
        schoolYear: "2023-2024",
        semester: "2nd Semester",
        totalUnits: 26,
        entries: [
          { code: "NSTP 120", title: "National Service Training Program 2", instructor: "N. Canoza", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "GE 120", title: "Purposive Communication", instructor: "O. Nida", finalGrade: 2.75, completedGrade: null, units: 3 },
          { code: "GE 123", title: "Reading in Philippine History", instructor: "C. Milagros", finalGrade: 2.5, completedGrade: null, units: 3 },
          { code: "GE 121", title: "Pagbasa tungo sa Pananaliksik", instructor: "E. Ejercito", finalGrade: 2.25, completedGrade: null, units: 3 },
          { code: "GE 122", title: "Advance Algebra and Trigonometry", instructor: "L. Hena", finalGrade: 2.25, completedGrade: null, units: 3 },
          { code: "ITE 121", title: "Computer Programming 2 (Advanced C Language)", instructor: "M. Abuke", finalGrade: 2.5, completedGrade: null, units: 3 },
          { code: "GE ELEC 1", title: "Reading Visual Arts", instructor: "C. Milagros", finalGrade: 2.5, completedGrade: null, units: 3 },
          { code: "PATHFIT 2", title: "Physical Activities Toward Health and Fitness 2 (Exercise-Based Fitness Activities)", instructor: "M. Mercader", finalGrade: 2.0, completedGrade: null, units: 2 },
          { code: "IT 120", title: "Introduction to Human Computer Interaction 1", instructor: "V. Camposano", finalGrade: 1.5, completedGrade: null, units: 3 },
        ],
      },
      {
        schoolYear: "2024-2025",
        semester: "1st Semester",
        totalUnits: 26,
        entries: [
          { code: "IT 221", title: "Integrative Programming Technologies 1", instructor: "A. Lutao", finalGrade: 1.75, completedGrade: null, units: 3 },
          { code: "IT ELEC 1", title: "Web System Technologies", instructor: "A. Lutao", finalGrade: 1.75, completedGrade: null, units: 3 },
          { code: "ITE 210", title: "Data Structure and Algorithm", instructor: "M. Abuke", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "APC 1", title: "Fundamentals of Database System", instructor: "M. Abuke", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "GE 210", title: "The Contemporary World", instructor: "E. Beros", finalGrade: 1.0, completedGrade: null, units: 3 },
          { code: "IT 211", title: "Discrete Mathematics", instructor: "V. Camposano", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "GE ELEC 2", title: "Living in the IT Era", instructor: "V. Camposano", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "GE 211", title: "Life and Works of Rizal", instructor: "R. Mijares", finalGrade: 1.25, completedGrade: null, units: 3 },
          { code: "PATHFIT 3", title: "Physical Activities Toward Health and Fitness 3 (Sports)", instructor: "S. Basiloy", finalGrade: 1.5, completedGrade: null, units: 2 },
        ],
      },
      {
        schoolYear: "2024-2025",
        semester: "2nd Semester",
        totalUnits: 26,
        entries: [
          { code: "GE 220", title: "Art Appreciation", instructor: "P. Eufracio", finalGrade: 2.0, completedGrade: null, units: 3 },
          { code: "IT 220", title: "Quantitative Methods (w/ Modeling & Simulation)", instructor: "A. Lutao", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "IT ELEC 2", title: "Integrative Programming Tech. 2 (OS Application)", instructor: "A. Lutao", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "PHILOS", title: "Logic", instructor: "A. Lutao", finalGrade: 1.75, completedGrade: null, units: 3 },
          { code: "IT 222", title: "Information Assurance & Security 1", instructor: "V. Camposano", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "IT ELEC 3", title: "Platform Technologies", instructor: "V. Camposano", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "PATHFIT 4", title: "Physical Activities Toward Health and Fitness 4 (Dance)", instructor: "M. Mercader", finalGrade: 1.75, completedGrade: null, units: 2 },
          { code: "ITE 220", title: "Application Development & Emerging Technologies", instructor: "M. Abuke", finalGrade: 2.25, completedGrade: null, units: 3 },
          { code: "ITE 221", title: "Information Management", instructor: "V. Camposano", finalGrade: 1.5, completedGrade: null, units: 3 },
        ],
      },
      {
        schoolYear: "2025-2026",
        semester: "1st Semester",
        totalUnits: 24,
        entries: [
          { code: "GE 310", title: "Ethics", instructor: "M. Alumbres", finalGrade: 2.0, completedGrade: null, units: 3 },
          { code: "APC 2", title: "Information Security & Risk Management", instructor: "A. Lutao", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "IT 311", title: "Networking 1", instructor: "A. Lutao", finalGrade: 1.25, completedGrade: null, units: 3 },
          { code: "APC 3", title: "Fundamentals of Data Mining", instructor: "K. Paller", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "IT 310", title: "Introduction to Human Computer Interaction 2", instructor: "J. Montañez", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "GE ELEC 3", title: "The Entrepreneurial Mind", instructor: "R. Mijares", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "IT ELEC 4", title: "Object-Oriented Programming", instructor: "M. Abuke", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "IT 312", title: "System Integration & Architecture 1", instructor: "M. Abuke", finalGrade: 1.5, completedGrade: null, units: 3 },
        ],
      },
      {
        schoolYear: "2025-2026",
        semester: "2nd Semester",
        totalUnits: 21,
        entries: [
          { code: "APC 4", title: "Data Mining Methodology", instructor: "C. Gales", finalGrade: 1.75, completedGrade: null, units: 3 },
          { code: "IT 330", title: "Social & Professional Issues", instructor: "M. Abuke", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "CAPS 410", title: "Capstone Project 1", instructor: "M. Abuke", finalGrade: 1.25, completedGrade: null, units: 3 },
          { code: "IT 321", title: "Networking 2 (Network Management)", instructor: "A. Lutao", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "APC 5", title: "Information Assurance & Security 2", instructor: "A. Lutao", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "APC 6", title: "Enterprise Data Management", instructor: "A. Lutao", finalGrade: 1.5, completedGrade: null, units: 3 },
          { code: "IT 322", title: "System Integration & Architecture 2", instructor: "M. Abuke", finalGrade: 1.5, completedGrade: null, units: 3 },
        ],
      },
      {
        schoolYear: "2026-2027",
        semester: "1st Semester",
        totalUnits: 9,
        entries: [
          { code: "CAPS 420", title: "Capstone Project 2", instructor: "M. Abuke", finalGrade: null, completedGrade: null, units: 3 },
          { code: "APC 7", title: "System Administration & Maintenance", instructor: "M. Abuke", finalGrade: null, completedGrade: null, units: 3 },
          { code: "APC 8", title: "Business Outsourcing", instructor: "C. Gales", finalGrade: null, completedGrade: null, units: 3 },
        ],
      },
    ],
  },
}