import type { StaffUser } from "@/types/staff/staff"

export const dummyStaffUsers: StaffUser[] = [
  {
    id: "STF-001",
    employeeId: "210001",
    firstName: "Elena",
    middleName: "Santos",
    lastName: "Mendoza",
    email: "elena.mendoza@nsc.edu.ph",
    password: "registrar123",
    position: "Chief Registrar",
    office: "Office of the Registrar",
    status: "active",
    role: "college_registrar",
  },
  {
    id: "STF-002",
    employeeId: "210002",
    firstName: "Ricardo",
    lastName: "Torres",
    email: "ricardo.torres@nsc.edu.ph",
    password: "registrar456",
    position: "Assistant Registrar",
    office: "Office of the Registrar",
    status: "active",
    role: "college_registrar",
  },
  {
    id: "STF-003",
    employeeId: "210003",
    firstName: "Marco",
    lastName: "Reyes",
    email: "marco.reyes@nsc.edu.ph",
    password: "admin123",
    position: "System Administrator",
    office: "IT Office",
    status: "active",
    role: "admin",
  },
  {
    id: "STF-004",
    employeeId: "210004",
    firstName: "Liza",
    lastName: "Fernandez",
    email: "liza.fernandez@nsc.edu.ph",
    password: "instructor123",
    position: "College Instructor",
    office: "College Department",
    status: "active",
    role: "instructor",
  },
  {
    id: "STF-005",
    employeeId: "210005",
    firstName: "Paolo",
    lastName: "Ramos",
    email: "paolo.ramos@nsc.edu.ph",
    password: "teacher123",
    position: "Basic Education Teacher",
    office: "Basic Education Department",
    status: "active",
    role: "teacher",
  },

  {
    id: "STF-007",
    employeeId: "210010",
    firstName: "Paolo",
    lastName: "Ramos",
    email: "paolo.ramos@nsc.edu.ph",
    password: "teacher123",
    position: "Basic Education Teacher",
    office: "Basic Education Department",
    status: "active",
    role: "president",
  },
]